### ISSUE TITLE
missing const from loadShader

### ISSUE THREAD

**Issue by Delwin9999** [jherico/Vulkan#18]
line 575 in vulkanContext.hpp

inline vk::PipelineShaderStageCreateInfo loadShader(const std::string& fileName, vk::ShaderStageFlagBits stage) { 

should be inline vk::PipelineShaderStageCreateInfo loadShader(const std::string& fileName, vk::ShaderStageFlagBits stage) const {

It only modifies the mutable member and right below it loadGlslShader is marked const.

**Comment by jherico** [comment]
fixed
