### ISSUE TITLE
vkx::Framebuffer segfaults on exit if there is no depth buffer

### ISSUE THREAD

**Issue by Delwin9999** [jherico/Vulkan#23]
Create a framebuffer with depthFormat == vk::Format::eUndefined and it will segfault on destruction.

To fix promote useDepth to a member variable and check it on destruction.

**Comment by jherico** [comment]
I think this is fixed by https://github.com/jherico/Vulkan/commit/98f0318b143ed4bbba9472893f20bd7d62671bbc
