### ISSUE TITLE
Fresh cloned, segmentation fault

### ISSUE THREAD

**Issue by elect86** [jherico/Vulkan#37]
Hi jherico,

- cloned the project
- ` cmake -G "Visual Studio 15 2017 Win64"`
- run `triangle`

and I get a segfault [here](https://imgur.com/a/8UAUL)

**Comment by jherico** [comment]
Fixed in https://github.com/jherico/Vulkan/commit/37a3f347bca361527cfc99a83ff1704b27fb533d

**Comment by jherico** [comment]
Sorry about that, I refactored my `Context` wrapper class to break up creation of the vk::Instance and vk::Device so that the surface could be created between the two operations, but didn't update this example to reflect that

**Comment by elect86** [comment]
No problem, thanks for solving it so fast!
