### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by prodev2015** [jherico/Vulkan#43]
Hello,

I am currently working on building the project named "vr_openxr" and there's an error while building the project. That is an "#include error" that says it can not find "openxr.hpp".  Where can I find the source file "openxr.hpp"?

Thank you.

**Comment by prodev2015** [comment]
Here is the code where the error occurs.
#include <vr/vr_common.hpp>
#include <math.h>
#include <openxr/openxr.hpp>  ----- cannot open source file "openxr/openxr.hpp"
#include <unordered_map>

**Comment by jherico** [comment]
At the time I wrote that, the `openxr.hpp` file (which contains the OpenXR C++ bindings) wasn't actually a part of the OpenXR SDK, so I had to manually build it.  It's since been incorporated into the version of the OpenXR SDK that's available in vcpkg.  I've updated the experimental/openxr branch to point to the more recent version of vcpkg with the missing file.  I'm attempting to test it locally now.

**Comment by prodev2015** [comment]
Thank you for your kind explanation. I've downloaded the missing file using vcpkg and built the project "vr_openxr". And then I got new errors in vr_openxr.cpp like the following.

E0289	no instance of constructor "xr::InstanceCreateInfo::InstanceCreateInfo" matches the argument list	vr_openxr	line: 164
E0289	no instance of constructor "xr::ActiveActionSet::ActiveActionSet" matches the argument list	vr_openxr	line: 507		

Please help me out with this. I would appreciate your help.

**Comment by jherico** [comment]
Try this code in the InstanceCreateInfo section

```
            xr::ApplicationInfo appInfo;
            strcpy(appInfo.applicationName, "vr_openxr");
            strcpy(appInfo.engineName, "vulkan_cpp_examples");
            appInfo.apiVersion = xr::Version::current();
            xr::InstanceCreateInfo ici{ {},
                                        appInfo,
                                         0,
                                         nullptr,
                                         (uint32_t)requestedExtensions.size(),
                                         requestedExtensions.data() };
```

on the line 507 error, replace `XR_NULL_PATH` with `{}`

**Comment by jherico** [comment]
I've updated my branch

**Comment by jimmybutler-2015** [comment]
I have passed all the errors above, but I've faced a weird error occurred in the "shader" project. The error is like the following.

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(230,5): error MSB6006: "cmd.exe" exited with code 9009.

Thank you in advance.

**Comment by prodev2015** [comment]
Great! It works now.
