### ISSUE TITLE
"vr_openxr" issue

### ISSUE THREAD

**Issue by prodev2015** [jherico/Vulkan#44]
Hello,
I am currently going to run the "vr_openxr" project, but the application crashes while running.
Does it need any runtime environment or something?
It crashes here in "vr_openxr.cpp". 
-> vr_openxr.cpp
line: 186            instance = xr::createInstance(ici);
-> openxr.hpp
line 3675      case Result::ErrorSessionRunning:
line 3676            throw SessionRunningError(message);

I would appreciate your help.

**Comment by prodev2015** [comment]
Here is the debug output.

'vr_openxr.exe' (Win32): Loaded 'C:\Windows\System32\MixedRealityRuntime.dll'. 
'vr_openxr.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. 
'vr_openxr.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. 
'vr_openxr.exe' (Win32): Loaded 'C:\Program Files\WindowsApps\Microsoft.WindowsMixedReality.Runtime_100.1910.1004.0_x64__8wekyb3d8bbwe\x64\WinXrRuntime.dll'. 
'vr_openxr.exe' (Win32): Loaded 'C:\Windows\System32\d2d1.dll'. 
'vr_openxr.exe' (Win32): Loaded 'C:\Windows\System32\dxgi.dll'. 
'vr_openxr.exe' (Win32): Loaded 'C:\Windows\System32\DWrite.dll'. 
'vr_openxr.exe' (Win32): Loaded 'C:\Windows\System32\D3D12.dll'. 
'vr_openxr.exe' (Win32): Loaded 'C:\Windows\System32\d3d11.dll'. 
Exception thrown at 0x00007FF81DF5A839 in vr_openxr.exe: Microsoft C++ exception: wxr::XrResultException at memory location 0x0000005A98CFAF70.
Error [GENERAL | xrCreateInstance | OpenXR-Loader] : LoaderInstance::CreateInstance chained CreateInstance call failed
Exception thrown at 0x00007FF81DF5A839 in vr_openxr.exe: Microsoft C++ exception: xr::exceptions::ExtensionNotPresentError at memory location 0x0000005A98CFC610.
Unhandled exception at 0x00007FF81DF5A839 in vr_openxr.exe: Microsoft C++ exception: xr::exceptions::ExtensionNotPresentError at memory location 0x0000005A98CFC610.

**Comment by jherico** [comment]
There has to be an OpenXR runtime installed on your machine in order for the sample to work.  

If you have an Oculus Rift headset, you can enable the runtime with some registry edits.  There is an article on how to do so here:  https://uploadvr.com/oculus-rift-basic-openxr-support/

There is also a Collabra runtime but I think it's only for Linux.  There is also an OpenXR runtime in the Microsoft Hololens drivers I believe, but I haven't tested with them and I don't know if the sample would work.

**Comment by prodev2015** [comment]
Wow! It works great. Thank you for your kind explanation and your time. I hope we'll have a good relationship with each other in the future.

**Comment by prodev2015** [comment]
Hello,  Excuse me, but help me with this please.  I am gong to integrate openxr into opengl, so i study the vr_openxr example. In the vr_openxr example, I don't understand why openxr.hpp is necessary and , how did you generate "openxr.hpp"?

**Comment by jherico** [comment]
The `openxr.hpp` isn't _necessary_.  It's a C++ wrapper around the C bindings provided by `openxr.h` that adds convenience and type safety.   

It's generated by scripts maintained at the project here:  https://github.com/KhronosGroup/OpenXR-Hpp  

However, the version I use it from my own fork:  project https://github.com/jherico/OpenXR-Hpp and has some fixes that have not yet been merged into the upstream project.  The version of the OpenXR loader that's available on vcpkg has my fixes as well.  If you use that version you should automatically get the openxr.hpp header.  You don't need to generated it yourself.

**Comment by prodev2015** [comment]
Thank you for your kind help, Mr Davis. I can't thank you enough for this.
