### ISSUE TITLE
subprojects are using a different method of downloading

### ISSUE THREAD

**Issue by Delwin9999** [jherico/Vulkan#8]
Using cmake to download the subprojects instead of bat/shell scripts makes sense but inside some firewalls the method you have is not going to work.

For gli/glm etc you've got a cutout if the zip file is manually placed in the right place but you don't have this cutout for vkcpp.  Could you please add the 'if it exists' check to vkcpp?  Thank you.

**Comment by Delwin9999** [comment]
Unfortunately I can't make pull requests from where I am (see above about funky firewall) but if you update the MD5 signature and uncomment it then vkcpp can be placed manually just like the others.

**Comment by jherico** [comment]
md5 sum added.
